import 'package:gestion_escom/ui/docentes/model/docente_model.dart';

class DocentePrueba {
  List<DocenteModel> getDocentes() {
    return [
      DocenteModel(
        numEmpleado: "123456",
        nombre: "Juan",
        primerApe: "Pérez",
        segundoApe: "Gómez",
        curp: "PEJG800101HDFRNS00",
        correo: "juan.perez@example.com",
        academia: "Ingeniería de Sistemas",
        ubicacion: "Edificio A, Oficina 101",
        auditoria: "Auditoría 1",
      ),
      DocenteModel(
        numEmpleado: "654321",
        nombre: "María",
        primerApe: "López",
        segundoApe: "Martínez",
        curp: "LOMM900202MDFRNS01",
        correo: "maria.lopez@example.com",
        academia: "Ingeniería Electrónica",
        ubicacion: "Edificio B, Oficina 202",
        auditoria: "Auditoría 2",
      ),
      DocenteModel(
        numEmpleado: "789012",
        nombre: "Carlos",
        primerApe: "Sánchez",
        segundoApe: "Díaz",
        curp: "SADC920303HDFRNS02",
        correo: "carlos.sanchez@example.com",
        academia: "Ciencias de la Computación",
        ubicacion: "Edificio C, Oficina 303",
        auditoria: "Auditoría 3",
      ),
      DocenteModel(
        numEmpleado: "101112",
        nombre: "Ana",
        primerApe: "Ramírez",
        segundoApe: "Hernández",
        curp: "RAHA760805MDFRNS04",
        correo: "ana.ramirez@example.com",
        academia: "Arquitectura",
        ubicacion: "Edificio D, Oficina 404",
        auditoria: "Auditoría 4",
      ),
      DocenteModel(
        numEmpleado: "121314",
        nombre: "Pedro",
        primerApe: "González",
        segundoApe: "Vázquez",
        curp: "GOEP900305HDFRNS05",
        correo: "pedro.gonzalez@example.com",
        academia: "Derecho",
        ubicacion: "Edificio E, Oficina 505",
        auditoria: "Auditoría 5",
      ),
      DocenteModel(
        numEmpleado: "131415",
        nombre: "Luisa",
        primerApe: "Martínez",
        segundoApe: "Pérez",
        curp: "MALP891203MDFRNS06",
        correo: "luisa.martinez@example.com",
        academia: "Psicología",
        ubicacion: "Edificio F, Oficina 606",
        auditoria: "Auditoría 6",
      ),
      DocenteModel(
        numEmpleado: "141617",
        nombre: "Ricardo",
        primerApe: "Torres",
        segundoApe: "Muñoz",
        curp: "TORM901230HDFRNS07",
        correo: "ricardo.torres@example.com",
        academia: "Física",
        ubicacion: "Edificio G, Oficina 707",
        auditoria: "Auditoría 7",
      ),
      DocenteModel(
        numEmpleado: "151718",
        nombre: "Sofía",
        primerApe: "Moreno",
        segundoApe: "González",
        curp: "MOGS940121MDFRNS08",
        correo: "sofia.moreno@example.com",
        academia: "Medicina",
        ubicacion: "Edificio H, Oficina 808",
        auditoria: "Auditoría 8",
      ),
      DocenteModel(
        numEmpleado: "161819",
        nombre: "Jorge",
        primerApe: "García",
        segundoApe: "Hernández",
        curp: "GAHJ870413HDFRNS09",
        correo: "jorge.garcia@example.com",
        academia: "Biología",
        ubicacion: "Edificio I, Oficina 909",
        auditoria: "Auditoría 9",
      ),
      DocenteModel(
        numEmpleado: "171920",
        nombre: "Raquel",
        primerApe: "Hernández",
        segundoApe: "Gutiérrez",
        curp: "HEGR930512MDFRNS10",
        correo: "raquel.hernandez@example.com",
        academia: "Historia",
        ubicacion: "Edificio J, Oficina 1010",
        auditoria: "Auditoría 10",
      ),
      DocenteModel(
        numEmpleado: "171920",
        nombre: "Marian Kelly",
        primerApe: "Guzman",
        segundoApe: "Mares",
        curp: "GUMA930512MDFRNS10",
        correo: "marian.kelly@example.com",
        academia: "Historia",
        ubicacion: "Edificio J, Oficina 1010",
        auditoria: "Auditoría 10",
      ),
    ];
  }
}
